title: "MPS Lab @ ASU"
description: "Making Programming Simple (MPS) Lab at Arizona State University"
url: "" # set to your production URL when deploying
baseurl: ""

markdown: kramdown
plugins:
  - jekyll-scholar

collections:
  research:
    output: true
    permalink: /research/:name/

scholar:
  style: apa
  sort_by: year
  order: descending
  bibliography: references
  source: ./_bibliography
  bibliography_template: bibentry
  repository: publications/papers
  details_dir: publications
  details_layout: publication.html
  query: "@*" # render all entries by default

# Google Scholar profile for Dr. Aviral Shrivastava
google_scholar: "https://scholar.google.com/citations?user=KMDOiEUAAAAJ&hl=en"

defaults:
  - scope:
      path: ""
      type: "research"
    values:
      layout: research

sass:
  style: compressed
